### ISSUE TITLE
Net::HTTP::Request.raw performance

### ISSUE THREAD

**Issue by dlowe** [ugexe/Perl6-Net--HTTP#16]
The .raw method of Net::HTTP::Request is very slow. This is mostly noticeable when trying to pass large payloads:

```
$ cat t.pl
#!/usr/bin/env perl6

use v6.c;

use lib '.';

use Net::HTTP::Request;
use Net::HTTP::URL;

for (1, 10, 100, 1000, 10000, 100000, 1000000, 10000000) -> $size {
   my $payload = 'x' x $size;
   my $request = Net::HTTP::Request.new(:url(Net::HTTP::URL.new("http://example.com")), :body($payload), :method('POST'));

   my $stime = now;
   my $bytes = $request.raw;
   say ".raw encoded $size bytes in " ~ (now - $stime) ~ " seconds";
}

$ ./t.pl
.raw encoded 1 bytes in 0.005756 seconds
.raw encoded 10 bytes in 0.0026722 seconds
.raw encoded 100 bytes in 0.00297342 seconds
.raw encoded 1000 bytes in 0.0046838 seconds
.raw encoded 10000 bytes in 0.01715308 seconds
.raw encoded 100000 bytes in 0.1457296 seconds
.raw encoded 1000000 bytes in 2.01509797 seconds
.raw encoded 10000000 bytes in 24.66715819 seconds
```

A trivial rewrite using multiple [push](https://docs.perl6.org/type/Buf#method_push) calls instead of trying to do everything in a single buf8.new does a lot better (this shouldn't be so much faster; might point to a rakudo issue? but anyway...):

```
.newraw encoded 1 bytes in 0.0059647 seconds
.newraw encoded 10 bytes in 0.00237580 seconds
.newraw encoded 100 bytes in 0.0040642 seconds
.newraw encoded 1000 bytes in 0.0031454 seconds
.newraw encoded 10000 bytes in 0.002099 seconds
.newraw encoded 100000 bytes in 0.0024765 seconds
.newraw encoded 1000000 bytes in 0.0119329 seconds
.newraw encoded 10000000 bytes in 0.10882793 seconds
```

my implementation is just:

```
+    method newraw {
+       my $b = buf8.new;
+       $b.push: self.start-line.encode;
+       $b.push: $CRLF;
+       $b.push: self!header-bin;
+       $b.push: $CRLF;
+       $b.push: $CRLF;
+       $b.push: self!body-bin;
+       $b.push: self!trailer-bin;
+       return $b;
+    }
```

Note that the `grep * ~~ Int,` is also removed from this version, but I also tried a version which *just* removed that grep, and it had ~ the same performance as the original. (However, I have no idea what that grep is for! Seems like it could mask usage errors?)

Sorry I can't pack this up as a PR. "It's complicated" :/

**Comment by dlowe** [comment]
And yes, I really am POSTing very large payloads via this library, IRL, and getting bitten by the multi-second encoding times!

**Comment by ugexe** [comment]
The `grep * ~~ Int` was replaced as returning `''.encode` instead of `''` from `body2bin` ( not sure why I did not do that originally ).

Thanks for the report.

**Comment by dlowe** [comment]
Thanks for the quick fix.  Can you make a release to p6c, too?

**Comment by ugexe** [comment]
It should propagate to p6c within an hour or so.

You can manually install it immediately via:
`zef install https://github.com/ugexe/Perl6-Net--HTTP/archive/47fbe8b70968e84e9209c57ad2dab1d6aaae3e8d.zip`
