### ISSUE TITLE
zero byte response from server throws ugly exception

### ISSUE THREAD

**Issue by dlowe** [ugexe/Perl6-Net--HTTP#17]
When an http server closes the connection abruptly, the thrown exception is "From argument to subbuf out of range. Is: -2, should be in 0..0":

```
#!/usr/bin/env perl6

use Net::HTTP::URL;
use Net::HTTP::Request;
use Net::HTTP::Transport;

my $server = start {
   my $listen = IO::Socket::INET.new( :listen,
      :localhost<localhost>,
      :localport(9999) );
   my $conn = $listen.accept;
   my $line = $conn.get;
   say $line;
   $conn.close;
};

my $url = Net::HTTP::URL.new("http://localhost:9999/");
my $request = Net::HTTP::Request.new(:$url, :body('foo'), :method('GET'), :header({}));
return Net::HTTP::Transport.new.round-trip($request);
```

I think it's correct to throw an exception under the circumstances, but I think this specific exception does a very poor job conveying the actual issue. A custom die along the lines of "Unexpected EOF in server response (while looking for CRLF)" whenever $buf is < 2 bytes would be a lot easier to understand :)

**Comment by ugexe** [comment]
Seems it will not be so simple.

```diff
diff --git a/lib/Net/HTTP/Utils.pm6 b/lib/Net/HTTP/Utils.pm6
index 32baf29..20caa2c 100644
--- a/lib/Net/HTTP/Utils.pm6
+++ b/lib/Net/HTTP/Utils.pm6
@@ -16,6 +16,7 @@ role IO::Socket::HTTP {
         my $buf = $.recv(1, :bin);

         repeat {
+            note $buf.bytes;
             my $byte = $.recv(1, :bin);
             last unless $byte.DEFINITE;
             $buf ~= $byte;
```
After applying this diff and modifying the example script to include `$conn.print("ab\r\n");` I get the following output:
```
GET / HTTP/1.1
1
2
3
4
0
"From argument to subbuf out of range. Is: -2, should be in 0..0
  in method get at /Users/ugexe/repos/Perl6-Net--HTTP/lib/Net/HTTP/Utils.pm6 (Net::HTTP::Utils) line 16
  in code  at /Users/ugexe/repos/Perl6-Net--HTTP/lib/Net/HTTP/Utils.pm6 (Net::HTTP::Utils) line 29
  in method round-trip at /Users/ugexe/repos/Perl6-Net--HTTP/lib/Net/HTTP/Transport.pm6 (Net::HTTP::Transport) line 30
  in block <unit> at test.pl6 line 20
```
so for some reason `$buf` loses its contents. And because a call to `$.recv` can return an empty `Buf` when its not finished reading I'm not entirely sure how I can make the necessary check (although INET sockets have been reworked since -- they used to be based on libuv async sockets -- so maybe `recv(1)` will block now until 1 byte is received and never return an empty `Buf` anymore).

**Comment by dlowe** [comment]
`$conn.print("ab\r\n")` is still an illegal HTTP response, though. A legal response AT MINIMUM has:
 1. status-line + CRLF
 2. one or more header lines, each terminated with CRLF
 3. CRLF indicating end of headers

... and I'm nearly certain that every case where $buf.bytes < 2 after the `repeat` block means the response was invalid.

**Comment by dlowe** [comment]
(in case it's not clear, the $buf isn't losing its contents *during* a call to get(), it's that round-trip calls get() more than once, and the *second* call to get() is breaking (correctly) because of the lack of CRLF.)

**Comment by ugexe** [comment]
> (in case it's not clear, the $buf isn't losing its contents during a call to get(), it's that round-trip calls get() more than once, and the second call to get() is breaking (correctly) because of the lack of CRLF.)

🤦‍♂️

**Comment by ugexe** [comment]
I don't think the check can occur after the `repeat` block since the exception is being thrown on the conditional expression that fires the loop block. So I changed the loop construct and check for a failure when reading the subbuf but before exploding the failure with `eq $CRLF`
