### ISSUE TITLE
Don't know how to parse content

### ISSUE THREAD

**Issue by JJ** [ugexe/Perl6-Net--HTTP#5]
I am getting this error
```
Don't know how to decode this content; call with the `:force` argument to try harder
  in method content at /home/jmerelo/.rakudobrew/moar-nom/install/share/perl6/site/sources/AE7C88757078A4662226580E08534ACBF2009301 (Net::HTTP::Response) line 74
  in sub MAIN at wikidata-query.p6 line 10
  in block <unit> at wikidata-query.p6 line 6
```
`.body` returns also a raw set of bytes:
```
Buf[uint8]:0x<7b 0a 20 20 22 68 65 61 64 22 20 3a 20 7b 0a 20 20 20 20 22 76 61 72 73 22 20 3a 20 5b 20 22 70 65 72 73 6f 6e 22 2c 20 22 70 65 72 73 6f 6e 4c 61 62 65 6c 22 20 5d 0a 20 20 7d 2c 0a 20 20 22 72 65 73 75 6c 74 73 22 20 3a 20 7b 0a 20 20 20 20 22 62 69 6e 64 69 6e 67 73 22 20 3a 20 5b 20 5d 0a 20 20 7d 0a 7d>
 ```

**Comment by ugexe** [comment]
What's the header? What's the actually body? Otherwise all I can tell you is exactly what the error says...

**Comment by JJ** [comment]
It's JSON, as in https://query.wikidata.org/sparql?format=JSON&query=SELECT%20?person%20?personLabel%20?occupation%20?occupationLabel%20WHERE%20%7B%0A%20%20?person%20wdt:P69%20wd:Q1232180.%20%0A%20%20?person%20wdt:P21%20wd:Q6581072.%0A%20%20?person%20wdt:P106%20?occupation%0A%20%20SERVICE%20wikibase:label%20%7B%09%09%09%09%0A%20%20%20%20bd:serviceParam%20wikibase:language%20%22es%22%20.%0A%20%20%7D%0A%7D%0A
Same error any other query, like this one https://query.wikidata.org/sparql?format=JSON&query=SELECT%20?person%20?personLabel%20WHERE%20%7B%0A%20%20%0A%20%20%20%20?person%20wdt:P69%20wd:Q1232180%20.%20%0A%20%20%20%20?person%20wdt:P21%20wd:Q6581072%20.%20%0A%20%20%0A%20%20%20%20SERVICE%20wikibase:label%20%7B%20%0A%20%20%20%20%20%20bd:serviceParam%20wikibase:language%20%22en%22%20.%0A%20%20%20%20%7D%0A%7D%20ORDER%20BY%20?personLabel
It works without a problem with HTTP::Client, though.

**Comment by ugexe** [comment]
If you want it to do guessing/non-strict decoding (security risk) like HTTP::Client you just do (as mentioned in the error) `.content(:force)` or just explicitly decode the body `.body.decode`/`.body.decode('latin-1')`/etc

`perl6 -MNet::HTTP::GET -e 'say Net::HTTP::GET("https://query.wikidata.org/sparql?format=JSON&query=SELECT%20?person%20?personLabel%20?occupation%20?occupationLabel%20WHERE%20%7B%0A%20%20?person%20wdt:P69%20wd:Q1232180.%20%0A%20%20?person%20wdt:P21%20wd:Q6581072.%0A%20%20?person%20wdt:P106%20?occupation%0A%20%20SERVICE%20wikibase:label%20%7B%09%09%09%09%0A%20%20%20%20bd:serviceParam%20wikibase:language%20%22es%22%20.%0A%20%20%7D%0A%7D%0A").content(:force)'`


`perl6 -MNet::HTTP::GET -e 'say Net::HTTP::GET("https://query.wikidata.org/sparql?format=JSON&query=SELECT%20?person%20?personLabel%20?occupation%20?occupationLabel%20WHERE%20%7B%0A%20%20?person%20wdt:P69%20wd:Q1232180.%20%0A%20%20?person%20wdt:P21%20wd:Q6581072.%0A%20%20?person%20wdt:P106%20?occupation%0A%20%20SERVICE%20wikibase:label%20%7B%09%09%09%09%0A%20%20%20%20bd:serviceParam%20wikibase:language%20%22es%22%20.%0A%20%20%7D%0A%7D%0A").body.decode'`

**Comment by JJ** [comment]
Thanks.
