### ISSUE TITLE
use the HTTP::Request and HTTP::Response roles

### ISSUE THREAD

**Issue by WildYorkies** [ugexe/Perl6-Net--HTTP#6]
https://github.com/perl6/perl6-http-server-threaded/blob/master/lib/HTTP/Server/Threaded/Response.pm6

https://github.com/perl6/perl6-http-server-threaded/blob/master/lib/HTTP/Server/Threaded/Request.pm6

re-using these roles instead of rolling your own can help make the ecosystem feel more connected

**Comment by ugexe** [comment]
https://github.com/ugexe/Perl6-Net--HTTP/blob/master/META6.json#L21

**Comment by WildYorkies** [comment]
Ah, I didn't know that was a goal
