### ISSUE TITLE
can't hit a url that ends in '/'

### ISSUE THREAD

**Issue by dlowe** [ugexe/Perl6-Net--HTTP#7]
I'd like to be able to access a url that ends in '/', for example '/foo/bar/'. The `pathify` function in Net::HTTP::Request unilaterally strips off the trailing '/'. (I can work around this, but it's annoying.)

As a consequence of the above, Net::HTTP::GET is also very badly broken in the case where the server actually replies to '/foo/bar' requests with a 302 redirect to '/foo/bar/'; since 'pathify' is applied to the url from the Location header; this ends up in a redirect loop :(

**Comment by ugexe** [comment]
Not sure why I had `pathify` stripping a trailing /, so I've removed that logic.

**Comment by dlowe** [comment]
Thanks, that's the fix I was hoping for :)
