### ISSUE TITLE
Net::HTTP::Request isn't thread safe (due to an apparent rakudo bug)

### ISSUE THREAD

**Issue by dlowe** [ugexe/Perl6-Net--HTTP#8]
I was able to narrow down concurrency bugs I've been having with Net::HTTP to this issue: https://rt.perl.org/Public/Bug/Display.html?id=131985.

While this is definitely a bug in Rakudo, it'd be nice if Net::HTTP::Request worked around it in the short term (by removing {} interpolating from `header2str`, `start-line` and `path`.)

Reproducing the problem is straightforward:

```
#!/usr/bin/env perl6

use v6.c;

use Net::HTTP::Request;
use Net::HTTP::URL;

await((1 .. 5).map: -> $tid {
   start {
      for (1 .. 100) -> $index {
         my $request = Net::HTTP::Request.new(:url(Net::HTTP::URL.new("http://www.google.com/$tid/$index/")), :method('GET'), :body(), :header({
            'Tid'   => $tid,
            'Index' => $index,
         }));
         my $s = ~$request;
         say "GET /$tid/$index ???? $s" unless $s ~~ /GET\s\/$tid\/$index\//;
         say "Tid: $tid        ???? $s" unless $s ~~ /Tid\:\s$tid/;
         say "Index: $index    ???? $s" unless $s ~~ /Index\:\s$index/;
      }
   }
});
```

**Comment by ugexe** [comment]
Thanks for discovering this as well as digging in to find the issue. I've added a test for this [here](https://github.com/ugexe/Perl6-Net--HTTP/commit/6a754d2326235bf97b5e5a5ebbf8d5edb7e4db4c#diff-0d232e3f2d8478e7a1f5ed9b2fe8e5c7)

**Comment by dlowe** [comment]
Excellent, thanks for the quick fix :)

**Comment by ugexe** [comment]
@dlowe just as a heads up [Cro](https://www.youtube.com/watch?v=6CsBDnTUJ3A) was released for Perl 6 in the last few days, which contains a http/http2 client among other things. [An example request](https://github.com/croservices/cro-http/blob/master/it/akamai.t).

`Net::HTTP` still may be what you want to use though. For one, `Cro` is asynchronous - and while this is usually a good thing (will scale infinitely-ish better) its probably easier for most to write things using blocking code. Additionally `Net::HTTP` has no dependencies (save for `IO::Socket::SSL`/`OpenSSL` if you visit https sites), while `Cro` has quite a few (some of which fail their tests; their site recommends installing with the `--/test` no test flag for what I presume is test failures resulting from optional features).

Ultimately `Net::HTTP` would do some things similarly, like returning a Response once the header is received and only blocking again if the response body is requested before the rest of the request is received (this simply wasn't possible until the 2017.07 release of moarvm, which allowed a socket to be read from a thread besides the one it originated from - a libuv limitation).

**Comment by dlowe** [comment]
Thanks for the pointer. For now, Net::HTTP is a better match for my use case, but I will keep an eye on Cro :)

**Comment by ugexe** [comment]
Fixed in rakudo with https://github.com/rakudo/rakudo/commit/59454b03cc3e12fd9236ecb980669f8712961141
