### ISSUE TITLE
Headers with false values are discarded

### ISSUE THREAD

**Issue by dlowe** [ugexe/Perl6-Net--HTTP#9]
Minor issue, but `header2str` uses `grep(*.value.so)`, therefore silently discards any header whose value is false:

```
> say Net::HTTP::Request.new(:url(Net::HTTP::URL.new('http://www.google.com/')), :body(), :method('GET'), :header({'Zero' => 0, 'False' => False, 'Empty' => ''})).Str
GET / HTTP/1.1
Host: www.google.com
```

I don't know whether you consider allowing numeric/boolean/whatever values for headers to be a bug. But even if you were to enforce String values on input, the grep is dubious (empty headers are allowed!)

**Comment by ugexe** [comment]
Thanks. I caught this as well looking into issue #8, and resolved it with 6a754d2
